FROM postgres:14.3

RUN apt-get update && apt-get install -y
RUN apt-get -y install net-tools
RUN apt-get -y install iputils-ping
RUN apt-get -y install apache2


WORKDIR destino/oto/backend

COPY data.js /tmp/oto/backend/database/data.js
COPY data.js / 
COPY sql.sql /

CMD bash

EXPOSE 5432
